### PR TITLE
Check if default_app_config is used on Django 1.7+

### LINKED ISSUE #39: Check if default_app_config is used on Django 1.7+
From https://docs.djangoproject.com/en/2.2/ref/applications/#configuring-applications:

> default_app_config allows applications that **predate Django 1.7** such as django.contrib.admin to opt-in to AppConfig features without requiring users to update their INSTALLED_APPS.
> **New applications should avoid default_app_config.** Instead they should require the dotted path to the appropriate AppConfig subclass to be configured explicitly in INSTALLED_APPS.

Unless someone opposes this idea, I'll try to throw together a PR for this soon.

### PR DESCRIPTION
**Pull request by denizdogan**
Fixes #39 

https://docs.djangoproject.com/en/2.2/ref/applications/#configuring-applications

### CODE REVIEW

**Comment by denizdogan** [comment]
@rocioar I think we need to look over the way that dependencies are handled in setuptools, tox and CircleCI, because this is a mess 😄  If you have time to help me get this CI build to pass, I'd appreciate it. Everything seems fine when I run it locally.

**Comment by washeck** [comment]
I ran into exactly the same problem in #38. Any help would be appreciated.

**Comment by rocioar** [comment]
@denizdogan @washeck This can be fixed by creating a requirements file on `requirements/testing.txt`,
 and then on `.circleci/config.yaml` replacing this line `pip install tox flake8 pytest-cov` with `pip install -r requirements/testing.txt`.

Let me know if that works!

Thank you

**Comment by rocioar** [comment]
I've moved the project to use poetry, closing this ticket.

You should be able to install dependencies with: `poetry install`

**Pull request closed without merging**
